### ISSUE TITLE
Some websites blocks scrolling with overflow-y hidden

### ISSUE THREAD

**Issue by ricobl** [NicolaeNMV/BehindTheOverlay#23]
The extension removes the overlay but scroll is blocked due to a `overflow-y: hidden`, usually on `html`, `body` or both nodes.

**Comment by NicolaeNMV** [comment]
Hi @ricobl, thanks for the suggestion.

Can you tell me what browser you're using and if you have an example of a website where this problem is ?

I have something in place to fix the scrolling. But only for "overflow" and not "overflow-y". Maybe that's the issue.
https://github.com/NicolaeNMV/BehindTheOverlay/blob/c31d96de2ec7a06f2b8e55bf118ccd9f24d655d5/chrome/js/overlay_remover.js#L144

**Comment by ricobl** [comment]
Hi @NicolaeNMV, thanks for the quick response.

Yeah, you're probably right.

I'm using Firefox 61.

Here is an example that applies `overflow-y` to both `html` and `body`:

https://www.techradar.com/au/news/the-best-headphones-deals-in-australia

**Comment by flarn2006** [comment]
Any updates on this?

**Comment by NicolaeNMV** [comment]
@flarn2006 sure, do you have an example website to reproduce with the problem ?

Cannot see any issues with https://www.techradar.com/au/news/the-best-headphones-deals-in-australia

**Comment by flarn2006** [comment]
I don't have a link handy at the moment but I know USA Today does it.

**Comment by NicolaeNMV** [comment]
Hey, I've now was able to reproduce and fix this issue. Thanks for the help !
